In [1]:
import os
import pandas as pd
import altair as alt

In [2]:
os.listdir(os.path.join("..", "data", "nintendo"))

['3DS.csv', 'DS.csv', 'Gamecube.csv', 'Switch.csv', 'Wii_WiiU.csv']

In [3]:
filename = "DS.csv"

In [4]:
df = pd.read_csv(os.path.join("..", 'data', "nintendo", filename))
df

,Product,Group,Geo,FY3/2005,FY3/2006,FY3/2007,FY3/2008,FY3/2009,FY3/2010,FY3/2011,...,FY3/2013,FY3/2014,FY3/2015,FY3/2016,FY3/2017,FY3/2018,FY3/2019,FY3/2020,FY3/2021,FY3/2022
0,Nintendo DS Lite,DS Lite,Japan,NaN,58,890,636,179,43,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nintendo DS Lite,DS Lite,The Americas,NaN,NaN,641,"1,065","1,174",525,183,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nintendo DS Lite,DS Lite,Other,NaN,NaN,596,"1,292","1,463",457,89,...,2,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Nintendo DSi,DSi,Japan,NaN,NaN,NaN,NaN,222,254,103,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nintendo DSi,DSi,The Americas,NaN,NaN,NaN,NaN,33,664,289,...,143,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Nintendo DSi,DSi,Other,NaN,NaN,NaN,NaN,48,562,274,...,11,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Nintendo DSi XL,DSi XL,Japan,NaN,NaN,NaN,NaN,NaN,104,118,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nintendo DSi XL,DSi XL,The Americas,NaN,NaN,NaN,NaN,NaN,42,366,...,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Nintendo DSi XL,DSi XL,Other,NaN,NaN,NaN,NaN,NaN,62,315,...,11,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Software,DS,Japan,382.0,"2,152","4,977","3,989","3,194","3,054","2,165",...,506,111.0,42.0,8.0,6.0,5.0,3.0,5.0,4.0,3.0
10,Software,DS,The Americas,475.0,"1,608","3,720","6,517","8,175","7,362","6,225",...,"1,763",538.0,145.0,86.0,11.0,NaN,NaN,NaN,NaN,NaN
11,Software,DS,Other,192.0,"1,235","3,658","8,056","8,362","4,743","3,707",...,"1,068",381.0,112.0,32.0,15.0,NaN,NaN,NaN,1.0,NaN
12,Nintendo DS,DS,Japan,212.0,420,22,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Nintendo DS,DS,The Americas,219.0,292,22,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Nintendo DS,DS,Other,95.0,376,185,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.iloc[:, 3:] = df.iloc[:, 3:].fillna("0").astype("string").apply(lambda x: x.str.replace(',', '').apply(lambda x: x.split(".")[0]).astype(int))
df

,Product,Group,Geo,FY3/2005,FY3/2006,FY3/2007,FY3/2008,FY3/2009,FY3/2010,FY3/2011,...,FY3/2013,FY3/2014,FY3/2015,FY3/2016,FY3/2017,FY3/2018,FY3/2019,FY3/2020,FY3/2021,FY3/2022
0,Nintendo DS Lite,DS Lite,Japan,0.0,58,890,636,179,43,14,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Nintendo DS Lite,DS Lite,The Americas,0.0,0,641,1065,1174,525,183,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Nintendo DS Lite,DS Lite,Other,0.0,0,596,1292,1463,457,89,...,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Nintendo DSi,DSi,Japan,0.0,0,0,0,222,254,103,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Nintendo DSi,DSi,The Americas,0.0,0,0,0,33,664,289,...,143,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Nintendo DSi,DSi,Other,0.0,0,0,0,48,562,274,...,11,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Nintendo DSi XL,DSi XL,Japan,0.0,0,0,0,0,104,118,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Nintendo DSi XL,DSi XL,The Americas,0.0,0,0,0,0,42,366,...,68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Nintendo DSi XL,DSi XL,Other,0.0,0,0,0,0,62,315,...,11,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Software,DS,Japan,382.0,2152,4977,3989,3194,3054,2165,...,506,111.0,42.0,8.0,6.0,5.0,3.0,5.0,4.0,3.0
10,Software,DS,The Americas,475.0,1608,3720,6517,8175,7362,6225,...,1763,538.0,145.0,86.0,11.0,0.0,0.0,0.0,0.0,0.0
11,Software,DS,Other,192.0,1235,3658,8056,8362,4743,3707,...,1068,381.0,112.0,32.0,15.0,0.0,0.0,0.0,1.0,0.0
12,Nintendo DS,DS,Japan,212.0,420,22,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Nintendo DS,DS,The Americas,219.0,292,22,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Nintendo DS,DS,Other,95.0,376,185,8,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
index_cols = ["Product", "Group", "Geo"]
df = df.melt(id_vars=index_cols, var_name="Date", value_name="Qty")
df

              Product    Group           Geo      Date  Qty
0    Nintendo DS Lite  DS Lite         Japan  FY3/2005  0.0
1    Nintendo DS Lite  DS Lite  The Americas  FY3/2005  0.0
2    Nintendo DS Lite  DS Lite         Other  FY3/2005  0.0
3        Nintendo DSi      DSi         Japan  FY3/2005  0.0
4        Nintendo DSi      DSi  The Americas  FY3/2005  0.0
..                ...      ...           ...       ...  ...
265          Software       DS  The Americas  FY3/2022  0.0
266          Software       DS         Other  FY3/2022  0.0
267       Nintendo DS       DS         Japan  FY3/2022  0.0
268       Nintendo DS       DS  The Americas  FY3/2022  0.0
269       Nintendo DS       DS         Other  FY3/2022  0.0

[270 rows x 5 columns]

In [7]:
df['dt'] = pd.to_datetime(df['Date'].str.replace('FY3/', '') + '-03-31')
df

              Product    Group           Geo      Date  Qty         dt
0    Nintendo DS Lite  DS Lite         Japan  FY3/2005  0.0 2005-03-31
1    Nintendo DS Lite  DS Lite  The Americas  FY3/2005  0.0 2005-03-31
2    Nintendo DS Lite  DS Lite         Other  FY3/2005  0.0 2005-03-31
3        Nintendo DSi      DSi         Japan  FY3/2005  0.0 2005-03-31
4        Nintendo DSi      DSi  The Americas  FY3/2005  0.0 2005-03-31
..                ...      ...           ...       ...  ...        ...
265          Software       DS  The Americas  FY3/2022  0.0 2022-03-31
266          Software       DS         Other  FY3/2022  0.0 2022-03-31
267       Nintendo DS       DS         Japan  FY3/2022  0.0 2022-03-31
268       Nintendo DS       DS  The Americas  FY3/2022  0.0 2022-03-31
269       Nintendo DS       DS         Other  FY3/2022  0.0 2022-03-31

[270 rows x 6 columns]

In [8]:
df = df.sort_values(["Group", "dt"], ascending=[True, True])

In [9]:
df["Qty"] = df["Qty"] * (10_000 / int(1e6))  # ten thousands to millions of units

In [10]:
year_max = 2016

df_filtered = df[df["dt"].dt.year <= year_max]

geo_totals = df_filtered[~df_filtered.Product.isin(["Software"])].groupby(["dt", "Geo"])["Qty"].sum().reset_index()
fy_totals = df_filtered[~df_filtered.Product.isin(["Software"])].groupby(["dt"])["Qty"].sum().reset_index()
# create a dense rank of "dt" column over each "Group" value, ensure dt is sorted first in ascending order

df_models = df_filtered.copy()
filter_rows = True
filter_rows &= ~df_models.Product.isin(["Software"])
# filter_rows &= df_models.Qty > 0
df_models = df_models[filter_rows]
df_models["GroupRank"] = df_models.groupby(["Group"])["dt"].rank(method="dense", ascending=True)

model_totals = df_models.groupby(["Group", "GroupRank", "dt"])["Qty"].sum().reset_index()
model_totals

      Group  GroupRank         dt    Qty
0        DS        1.0 2005-03-31   5.26
1        DS        2.0 2006-03-31  10.88
2        DS        3.0 2007-03-31   2.29
3        DS        4.0 2008-03-31   0.08
4        DS        5.0 2009-03-31    0.0
5        DS        6.0 2010-03-31    0.0
6        DS        7.0 2011-03-31    0.0
7        DS        8.0 2012-03-31    0.0
8        DS        9.0 2013-03-31    0.0
9        DS       10.0 2014-03-31    0.0
10       DS       11.0 2015-03-31    0.0
11       DS       12.0 2016-03-31    0.0
12  DS Lite        1.0 2005-03-31    0.0
13  DS Lite        2.0 2006-03-31   0.58
14  DS Lite        3.0 2007-03-31  21.27
15  DS Lite        4.0 2008-03-31  29.93
16  DS Lite        5.0 2009-03-31  28.16
17  DS Lite        6.0 2010-03-31  10.25
18  DS Lite        7.0 2011-03-31   2.86
19  DS Lite        8.0 2012-03-31   0.77
20  DS Lite        9.0 2013-03-31   0.02
21  DS Lite       10.0 2014-03-31    0.0
22  DS Lite       11.0 2015-03-31    0.0
23  DS Lite       12.0 2016-03-31   0.01
24      DSi        1.0 2005-03-31    0.0
25      DSi        2.0 2006-03-31    0.0
26      DSi        3.0 2007-03-31    0.0
27      DSi        4.0 2008-03-31    0.0
28      DSi        5.0 2009-03-31   3.03
29      DSi        6.0 2010-03-31   14.8
30      DSi        7.0 2011-03-31   6.66
31      DSi        8.0 2012-03-31   2.29
32      DSi        9.0 2013-03-31   1.54
33      DSi       10.0 2014-03-31   0.11
34      DSi       11.0 2015-03-31   0.01
35      DSi       12.0 2016-03-31    0.0
36   DSi XL        1.0 2005-03-31    0.0
37   DSi XL        2.0 2006-03-31    0.0
38   DSi XL        3.0 2007-03-31    0.0
39   DSi XL        4.0 2008-03-31    0.0
40   DSi XL        5.0 2009-03-31    0.0
41   DSi XL        6.0 2010-03-31   2.08
42   DSi XL        7.0 2011-03-31   7.99
43   DSi XL        8.0 2012-03-31   2.03
44   DSi XL        9.0 2013-03-31    0.8
45   DSi XL       10.0 2014-03-31   0.01
46   DSi XL       11.0 2015-03-31   0.01
47   DSi XL       12.0 2016-03-31    0.0

In [11]:
model_totals_chart = alt.Chart(model_totals).mark_line(point={"shape": "square", "size": 50}).encode(
    x=alt.X('dt:T'),
    y=alt.Y('Qty:Q'),
    color=alt.Color('Group:N')
)

fiscal_year_totals_chart = alt.Chart(fy_totals).mark_line(color='black', strokeDash=[5, 5], point={"shape": "square", "size": 50, "color": "black"}).encode(
    x=alt.X('dt:T'),
    y=alt.Y('Qty:Q'),
)


chart = fiscal_year_totals_chart + model_totals_chart
chart.interactive()

alt.LayerChart(...)

In [12]:
chart.save("../figs/DS_Models_vs_Total.png")